import './globals.css';
import { ReactNode } from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="lenis">
      <body className="bg-aicon-bone text-aicon-ink font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
